package frc.robot.swerve;

public enum SwerveState {
  TELEOP,
  TELEOP_SNAPS,
  AUTO,
  AUTO_SNAPS,
  INTAKE_ASSIST_TELEOP,
  INTAKE_ASSIST_AUTO,
  PURPLE_ASSIST_TELEOP,
  PURPLE_ASSIST_AUTO,
  PURPLE_SNAP_TELEOP,
  PURPLE_SNAP_AUTO,
  PURPLE_APPROACH_TELEOP,
  PURPLE_APPROACH_AUTO;
}
